version: “3.8”

services:
  password_bot1:
    build: ./
    command: ./main
    env_file:
    - .env
    ports:
    - "8000:8000"
    depends_on:
    - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
    - "27017:27017"
    command: mongod